# docker-compose.yml
version: '3.0'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    hostname: db
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: fastfeet
    ports:
      - '5432:5432'
    expose:
      - 5432

  redis:
    container_name: fastfeet_redis
    restart: always
    image: redis:alpine
    hostname: redis
    expose:
      - 6379

  fastfeet:
    container_name: fastfeet
    restart: always
    entrypoint: ['/bin/bash', './start.sh']
    build: .
    depends_on:
      - db
      - redis
    ports:
      - '3333:3000'
